---
theme: jekyll-theme-minimal
title: Xiangrong Wang (王向荣)
description: Posdoc in Delft University of Technology
---
![img](https://github.com/xiangrongwang/xiangrongwang.github.io/blob/master/xiangrong.jpeg)
