theme: jekyll-theme-minimal
title: Xiangrong Wang 王向荣
description: Postdoc in Delft University of Technology
permalink: pretty
![img](https://github.com/xiangrongwang/xiangrongwang.github.io/blob/master/xiangrong.jpeg)
