theme: jekyll-theme-minimal
title: Xiangrong Wang (王向荣)
locale: en_US
description: Postdoc in Delft University of Technology

owner:
  name: Xiangrong Wang
  avatar: xiangrong.jpeg
  bio: "Postdoc in Delft University of Technology."
  email: x.wang-2@tudelft.nl
